name: click-in-every-day

on:
  # 每天 9:00 自动打卡 -- 1:00 是 UTC 时间
  schedule:
    - cron: '0 1 * * *'
  # 手动执行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 在 runner 中安装 Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # 安装 pnpm 包管理工具
      - name: Use pnpm package manager
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # 安装依赖
      - name: Installing Dependencies
        run: pnpm i --frozen-lockfile

      # 缓存打包结果
      - name: Cache Bundle
        id: cache-bundle
        uses: actions/cache@v3
        with:
          path: 'dist/gzhu-health-clock-in.cjs'
          key: ${{runner.OS}}-${{hashFiles('dist/gzhu-health-clock-in.cjs')}}

      # 打包
      - name: Build
        if: steps.cache-bundle.outputs.cache-hit != 'true'
        run: pnpm build

      # 运行打包结果
      - name: Start Clock In
        env:
          GZHU_USERNAME: ${{secrets.GZHU_USERNAME}}
          GZHU_PASSWORD: ${{secrets.GZHU_PASSWORD}}
        run: node dist/gzhu-health-clock-in.cjs
